### ISSUE TITLE
当前item 不够一页 并不能加载更多

### ISSUE THREAD

**Issue by LikeQuite** [nukc/LoadMoreWrapper#10]

**Comment by nukc** [comment]
请参考 demo，如果不行，请提供详细的信息

**Comment by LikeQuite** [comment]
我将其封装在父类里面,   初始化的时候会调一次,  之后item 没有铺满屏幕时, 不能上拉

**Comment by nukc** [comment]
onLoadMore 没有回调吗？是不是 ```setLoadMoreEnabled(false)``` 了？正常的情况下，item 没有铺满都会回调 onLoadMore

**Comment by LikeQuite** [comment]
没有的.   setLadMoreEnabled(true)     onLoadMore  也没有回调

**Comment by nukc** [comment]
能否提供关键代码

**Comment by LikeQuite** [comment]
能加扣扣吗?

**Comment by nukc** [comment]
QQ353932158
