### ISSUE TITLE
 为什么进入recyclerview未到底部还是调用了onLoadMore呢

### ISSUE THREAD

**Issue by narakai** [nukc/LoadMoreWrapper#11]
为什么进入recyclerview未到底部还是调用了onLoadMore呢？

**Comment by nukc** [comment]
item 是不是未铺满屏幕？

**Comment by narakai** [comment]
铺满了的，我换了个你以前版本的，好了。但是又出现一个问题，loadmore会加载两次，布局会多一行。

**Comment by nukc** [comment]
你是使用哪个版本？还有需要更详细的信息，比如初始化数据有多少（初始化是否铺满，铺满的话是超过屏幕多少），加载一次有多少数据，布局多一行是什么布局等

**Comment by narakai** [comment]
sorry, 刚看了下，是第一次loadmore(满屏)后，加载了数据并且刷新，但是第二次的数据没满屏。

**Comment by nukc** [comment]
第二次 loadmore 还没有满屏的话，还是会再次回调的，所以需要使用者自己判断是否还有更多，没有的话就 ```setLoadMoreEnabled(false)``` 就可以了。

**Comment by narakai** [comment]
setLoadMoreEnabled(false)后，没有回调onLoadmore了，但是loading动画还在...

**Comment by narakai** [comment]
mWrapper.setListener(new LoadMoreAdapter.OnLoadMoreListener() {
            @Override
            public void onLoadMore(LoadMoreAdapter.Enabled enabled) {
                if (mStep.getList().size() < PAGE_SIZE || mPage > 3) {
                    Log.d(TAG, "onLoadMore: false");
                    enabled.setLoadMoreEnabled(false);
                } else {
                    Log.d(TAG, "onLoadMore: true");
                    enabled.setLoadMoreEnabled(true);
                    mPage += 1;
                    getList();
                }
            }
        }).into(mResultsRecyclerView);

代码大概是这样

**Comment by nukc** [comment]
还需要调用 notify 进行刷新。
可以参考如下 getList() 方法里有调用 notify 吧
```java
    public void onLoadMore(LoadMoreAdapter.Enabled enabled) {
        // 不合需求的话，再修改判断
        if (mStep.getList().size() < PAGE_SIZE || mPage > 3) {
            Log.d(TAG, "onLoadMore: false");
            enabled.setLoadMoreEnabled(false);
        } 

        mPage += 1;
        // 当不启用 loadmre 后也调用，这样 rv 刷新后就不会有 loading view 了
        getList();
    }

```

**Comment by narakai** [comment]
明白了 问题解决 谢谢。
