### ISSUE TITLE
vlayout 加载更多发现问题

### ISSUE THREAD

**Issue by douya40** [nukc/LoadMoreWrapper#16]
加载更多的时候，数据还没有加载完点击重新获取数据，整个vlayout的recyclview会置顶

**Comment by nukc** [comment]
那数据加载完，再点击重新获取数据呢？

**Comment by nukc** [comment]
重新获取数据后，是 refresh 重新赋值了数据 还是在原有的数据 add ？还是 clean 原有的数据后再 add ?可以提供相应的代码 demo 吗
