### ISSUE TITLE
function request 

### ISSUE THREAD

**Issue by DeevD** [nukc/LoadMoreWrapper#17]
When loading ... if network request is fail load more fail view set on loading view bro :D and retry function also bro :D

**Comment by nukc** [comment]
```java
 .setLoadMoreEnabled(false); 
```

**Comment by DeevD** [comment]
Yes bro i know that funtion .. i mean when  load fail .. add new footer for retry view bro :D

**Comment by nukc** [comment]
Ok，I will add it in the future

**Comment by DeevD** [comment]
Thank bro

**Comment by nukc** [comment]
@DeevD please check it, supported in v1.7.0

**Comment by nukc** [comment]
when load failed, you can:
```java
enabled.setLoadFailed(true);
// or
mLoadMoreWrapper.setLoadFailed(true);
```

**Comment by DeevD** [comment]
Thank you so much bro i will check now ..
