### ISSUE TITLE
 private LoadMoreAdapter.Enabled mEnabled;  mEnabled.setLoadMoreEnabled(false)无效

### ISSUE THREAD

**Issue by Li-GuangLiang** [nukc/LoadMoreWrapper#18]
private LoadMoreAdapter.Enabled mEnabled; 
 @Override
    public void onLoadMore(LoadMoreAdapter.Enabled enabled) {
        mEnabled = enabled;
        //网络请求
    }
在网络请求后发现无更多数据， mEnabled.setLoadMoreEnabled(false);无效，但是在网络请求出错时  mEnabled.setLoadFailed(true);有效

**Comment by nukc** [comment]
请看 https://github.com/nukc/LoadMoreWrapper/issues/7
mEnabled.setLoadFailed(true); 方法里已经调用了 notify.
但是 mEnabled.setLoadMoreEnabled(false); 没有，需要自行调用 notify 方法。

**Comment by Li-GuangLiang** [comment]
感谢！ 个人建议新增一个ShowNoMore( )方法，方便调用。

**Comment by nukc** [comment]
嗯，有必要的话，看什么时候我重构一次。
