### ISSUE TITLE
Can't hidden progress bar for loadmore loading bro 

### ISSUE THREAD

**Issue by DeevD** [nukc/LoadMoreWrapper#19]
private fun initLoadMore(view: View) {
        var load = LoadMoreWrapper.with(categoriesAllAdapter)
                .setFooterView(-1)
                .setNoMoreView(R.layout.base_no_more)
                .setNoMoreView(view)
                .setListener({ enabled ->
                    Log.i(TAG, "listener page $page last page : $lastPage")
                    if (page >= lastPage) {
                        Log.i(TAG, "no more to load")
                        enabled.loadMoreEnabled =false
                        mLoadMoreWrapper.setShowNoMoreEnabled(true  )
                    } else {
                        categoriesAllRv.post({ apicall(true) })
                    }
                }).setLoadMoreEnabled(true)
                .into(categoriesAllRv)
        mLoadMoreWrapper = LoadMoreWrapper(load)
    }

**Comment by nukc** [comment]
please notify after setLoadMoreEnabled
