### ISSUE TITLE
vlayout    在满屏情况下连续多次回调onLoadMore

### ISSUE THREAD

**Issue by Zwang0729** [nukc/LoadMoreWrapper#20]
vlayout    在满屏情况下连续多次回调onLoadMore
vlayout中有banner，有grid九宫格item，还有linear item等多种item

**Comment by nukc** [comment]
@douya40 你有遇到过吗

**Comment by nukc** [comment]
你看看这个 fork [treasure-lau/LoadMoreWrapper](https://github.com/treasure-lau/LoadMoreWrapper) 是否解决了你的问题
