### ISSUE TITLE
加载更多会出现延迟

### ISSUE THREAD

**Issue by suoyo** [nukc/LoadMoreWrapper#21]
参考一下[上拉加载延迟](https://github.com/jdsjlzx/LRecyclerView/issues/263)

**Comment by nukc** [comment]
写了个简单的 demo，但是并没有出现这个问题，[ScrollingActivity.java](https://github.com/nukc/LoadMoreWrapper/blob/master/app/src/main/java/com/github/nukc/sample/ScrollingActivity.java) , [activity_scrolling.xml](https://github.com/nukc/LoadMoreWrapper/blob/master/app/src/main/res/layout/activity_scrolling.xml)。
