### ISSUE TITLE
首次进入页面会自动加载更多？

### ISSUE THREAD

**Issue by evansherry** [nukc/LoadMoreWrapper#25]
首次进入页面adapter.getItemCount为0，LoadMoreAdapter会添加一个footer, 然后会加载更多，ui看起来很奇怪，因为加载更多在顶部，位置接近SwipeRefreshLayout下拉的地方。

**Comment by nukc** [comment]
是会的，因为未铺满屏幕的时候会触发加载更多方法，假如在A手机加载10个铺满了屏幕还可以往下滑动，触发加载更多是在这一块的逻辑 [LoadMoreAdapter.java#L277-L314#OnScrollListener](https://github.com/nukc/LoadMoreWrapper/blob/e08a0b89116bda75bc2e0b835182bcdac3c44b83/loadmorewrapper/src/main/java/com/github/nukc/LoadMoreWrapper/LoadMoreAdapter.java#L277-L314) ，这个是一般情况下。但是同样的数据在B手机10个未铺满屏幕，这个时候 OnScrollListener 是无法触发的，但是也是需要再触发一次加载更多以确认是否还有更多数据。这个时候就在 [LoadMoreAdapter.java#L114-L125](https://github.com/nukc/LoadMoreWrapper/blob/e08a0b89116bda75bc2e0b835182bcdac3c44b83/loadmorewrapper/src/main/java/com/github/nukc/LoadMoreWrapper/LoadMoreAdapter.java#L114-L125) 进行了判断

**Comment by evansherry** [comment]
首次进入会显示加载更多的footer,  没办法关掉，尝试设置loadMoreEnable为false, 会改变mShouldRemove标识，最终还是显示footer，只能修改源码了。 原因是进入页面会有一个loading dialog，这时候底部出现一个加载更多，看起来很奇怪。

**Comment by nukc** [comment]
安排，但近期比较忙

**Comment by nukc** [comment]
@evansherry 使用 ``setNotShowFooterWhenNotCoveredScreen(true) ``
