### ISSUE TITLE
FlexboxLayoutManager support?

### ISSUE THREAD

**Issue by amanzan** [nukc/LoadMoreWrapper#26]
Does it support FlexboxLayoutManager for RecyclerView?

**Comment by nukc** [comment]
Please see: https://github.com/nukc/LoadMoreWrapper/blob/master/loadmorewrapper/src/main/java/com/github/nukc/LoadMoreWrapper/LoadMoreAdapter.java#L306-L323

**Comment by nukc** [comment]
No special support [FlexboxLayoutManager](https://github.com/google/flexbox-layout/blob/main/flexbox/src/main/java/com/google/android/flexbox/FlexboxLayoutManager.java)
Welcome PR
