### ISSUE TITLE
DataObserver is not correct when using with ListAdapter

### ISSUE THREAD

**Issue by namnh-0652** [nukc/LoadMoreWrapper#27]
Thanks for your hard work!
The callbacks of [`AdapterDataObserver`](https://github.com/nukc/LoadMoreWrapper/blob/master/loadmorewrapper/src/main/java/com/github/nukc/LoadMoreWrapper/LoadMoreAdapter.java#L461) do not call "same" when using `ListAdapter` (submitList) vs normal `RecyclerAdapter`.

I still do not find the root cause (investigating) but I want to share this, if you find any thing new, please mention me. 
Thanks !

**Comment by nukc** [comment]
need register observer
[LoadMoreAdapter.java#L66](https://github.com/nukc/LoadMoreWrapper/blob/master/loadmorewrapper/src/main/java/com/github/nukc/LoadMoreWrapper/LoadMoreAdapter.java#L66)

**Comment by namnh-0652** [comment]
@nukc 
Yes, it already registered.
I've checked, it seems I make wrong `DiffUtil.ItemCallback` implementation.
I will close this and back if there is any problem.
Thanks !
