### ISSUE TITLE
赞一个，顺便问一下...............

### ISSUE THREAD

**Issue by cjcj125125** [nukc/LoadMoreWrapper#4]
这个加载更多能不能加上下拉刷新？这样就更完美了，一直认为手动上拉加载更多不是很好，望楼主赐教，谢谢

**Comment by nukc** [comment]
下拉加载并不在本库的范围，下拉加载有官方 v4 包的 ```SwipeRefreshLayout```，想要自定义强的第三方有 [android-Ultra-Pull-To-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh) 等，或者我的另一个库 [DistRefreshLayout](https://github.com/nukc/DistRefreshLayout)
