### ISSUE TITLE
README 写的不对。

### ISSUE THREAD

**Issue by hnlbxb2004** [nukc/LoadMoreWrapper#6]
README 里面
dependencies {
        compile 'com.github.nukc:LoadMoreWrapper:v1.2'
    }

应该是
   compile 'com.github.nukc:LoadMoreWrapper:v1.2'

V1.2  不是1.2  ，1.2 拉不下，v1.2 才能拉下来。

**Comment by nukc** [comment]
``` compile 'com.github.nukc:LoadMoreWrapper:1.2' ``` 是 jcenter 仓库；详情：https://bintray.com/nukc/maven/LoadMoreWrapper

``` compile 'com.github.nukc:LoadMoreWrapper:v1.2' ```是 jitpack 仓库。详情：https://jitpack.io/#nukc/LoadMoreWrapper/v1.2

gradle 默认是：
```gradle
allprojects {
    repositories {
        jcenter()
    }
}
```
所以直接 ```gradle compile 'com.github.nukc:LoadMoreWrapper:1.2' ```是直接可以的，因为我之前上传到 jcenter 的时候出了点问题，为了能正常依赖使用 jitpack 也是可以的，只是使用 jitpack 仓库需要多一步配置：
```gradle
allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```
