### ISSUE TITLE
setLoadMoreEnabled(false)无效

### ISSUE THREAD

**Issue by narakai** [nukc/LoadMoreWrapper#7]
viewpager 里的 recycler view，loadmore的时候判断获取数据小于期望数据的时候设置setLoadMoreEnabled(false)，但是下面小圆仍然在转，不知道是怎么回事？

**Comment by nukc** [comment]
是否 ViewPager 来回切换后，loadingView 仍然显示？

**Comment by narakai** [comment]
并没有切换，一直往下拉的，直到没有数据

**Comment by nukc** [comment]
LoadMoreWrapper 是哪个版本？如果可以的话，能否贴下关键代码或者 demo？

**Comment by narakai** [comment]
observableMore.subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).compose(MainLevelUpFragment.this.<String>bindToLifecycle())
                            .subscribe(new Observer<String>() {

                                @Override
                                public void onCompleted() {
                                    if (mHasError) {
                                        enabled.setLoadMoreEnabled(false);
                                    }
                                }

                                @Override
                                public void onError(Throwable e) {
                                    enabled.setLoadMoreEnabled(false);
                                    mHasError = true;
                                    Log.d(TAG, "onError: " + e.getMessage());
                                }

                                @Override
                                public void onNext(String s) {
                               //do something
}

**Comment by narakai** [comment]
error的时候表示请求不到更多数据，然后让它不显示，但是无效

**Comment by narakai** [comment]
我解决了，重新刷了一次界面。貌似enabled.setLoadMoreEnabled(false)这个在界面已有loading动画的情况下取消不掉动画

**Comment by nukc** [comment]
是的，使用 ```enabled.setLoadMoreEnabled(false)``` 之后还需要 notify 进行更新。
setLoadMoreEnabled 并不会刷新界面（可以查看源码具体实现），具体刷新时间由开发者自己决定。

**Comment by nukc** [comment]
```enabled.setLoadMoreEnabled(false)``` 是告诉它下次工作的时候要把 loadingView 给移除。

**Comment by nukc** [comment]
如果你还有什么问题或者好的建议，欢迎反馈，直接提 PR 也是可以的。

**Comment by narakai** [comment]
好的 明白了 谢谢解答。
