### ISSUE TITLE
获取失败

### ISSUE THREAD

**Issue by chowaikong** [nukc/LoadMoreWrapper#8]
我按照 README 的配置提示获取失败了，执行 `./gradlew build --info` 之后发现
`Resource missing. [HTTP GET: https://jcenter.bintray.com/com/github/nukc/LoadMoreWrapper/1.2/LoadMoreWrapper-1.2.pom]
Resource missing. [HTTP HEAD: https://jcenter.bintray.com/com/github/nukc/LoadMoreWrapper/1.2/LoadMoreWrapper-1.2.jar]
Resource missing. [HTTP GET: https://jitpack.io/com/github/nukc/LoadMoreWrapper/1.2/LoadMoreWrapper-1.2.pom]
Resource missing. [HTTP HEAD: https://jitpack.io/com/github/nukc/LoadMoreWrapper/1.2/LoadMoreWrapper-1.2.jar]
`  
搜了一下可能是源重复了 https://github.com/jitpack/jitpack.io/issues/424  
我有两个项目同时需要从 jcenter 和 jitpack.io 获取第三方库，这两个项目都不能获取你的库，然后我另外一个没有添加 jitpack.io 源的项目就可以获取你的库了，不知道这应该怎么解决？

**Comment by nukc** [comment]
是 ```compile 'com.github.nukc:LoadMoreWrapper:v1.2'``` 吗？   jitpack 的1.2前面是有个 v 的

**Comment by nukc** [comment]
https://jitpack.io/com/github/nukc/LoadMoreWrapper/v1.2/LoadMoreWrapper-v1.2.pom 是有的，有 v 的

**Comment by nukc** [comment]
使用 ```compile 'com.github.nukc:loadmorewrapper:1.2'``` 看看是否能解决

**Comment by chowaikong** [comment]
改为小写可以了，感谢解答。

**Comment by nukc** [comment]
我的锅，我已经更新 README.md 把大写改小写了。
